### ISSUE TITLE
Provide sample app as APK

### ISSUE THREAD

**Issue by rugk** [westnordost/countryboundaries#1]
For easy testing/debugging it would be nice if you could just create a release in this repo and attach the sample app there. (Did not test the app yet, but I hope it would help for cases like https://github.com/westnordost/StreetComplete/issues/1007)

**Comment by matkoniecz** [comment]
Anyone that would debug is also capable of building .apk.

For remote debugging whoever is investigating problem is able to provide .apk file.

**Comment by rugk** [comment]
Not in the too technical sense of debugging, i.e. not with a debugger. 

It's just person XYZ has a problem with location (see issue), and they have no dev experience/Android studio. But anyone can just download an APK and test it. That's way easier than installing Android Studio.

**Comment by westnordost** [comment]
No, I don't want to supply this.
