### ISSUE TITLE
Some issue with dataset regarding Ukranian regions

### ISSUE THREAD

**Issue by Zamirk** [westnordost/countryboundaries#13]
Hi

Crimea and Sevastopol should have the country codes `UA` for Ukraine, `RU` for Russia, and its country subdivision code, which is `UA-43` and `UA-40` respectively.
For some reason, they only have the `subdivision code`, and `RU`.

All other countries which have regions containing subdivision codes also share the "parent" country code it is part of.

For example, Greenland will return `GL` and `DK` for Denmark.

Sevastopol 
Latitude and longitude
44.629650
33.535667

Result

RU / UA-40

Expected result

RU / UA-40 / UA

Crimea 
Latitude and longitude
45.3453
34.4997

Result

RU / UA-43

Expected result

RU / UA-43 / UA

**Comment by westnordost** [comment]
It seems I overlooked this issue. Anyway, whatever this library returns depends on the data fed into it. If you need different output for your application, you need to use different data or modify it. See https://github.com/westnordost/countryboundaries#data
