### ISSUE TITLE
Adding German states?

### ISSUE THREAD

**Issue by wetneb** [westnordost/countryboundaries#15]
I am exploring what it would take to enable StreetComplete's smoking quest automatically in regions of the world where it would be relevant, by compiling a list of countries where indoor smoking is possible in bars or other public places.

In Germany the situation depends on the federal state, for instance with Saarland banning indoor smoking but Saxony allowing it.

Therefore it would be useful if this library would be able to return not just `DE` but more granular ISO 3166-2 codes such as `DE-SL` (Saarland) or `DE-SN` (Saxony). I believe this could be interesting to take into account other regulatory differences between the states (in the context of StreetComplete). It would follow the existing pattern already used for the USA and other countries.

Would such a granularity be fitting for this library?

It seems that the JOSM data file you use to generate the binary file does not contain those sub-regions does not contain this information. I wonder if it could be added separately, or if I should rather convince JOSM to include it in their own file.

**Comment by westnordost** [comment]
This library has nothing to do with that. It only parses and works with whatever boundaries file is supplied.
So, this is rather a ticket for streetcomplete. Anyway, for the current JOSM boundaries file it is rather consistent which boundaries are included and which are not included. All state boundaries and boundaries of autonomous regions are included. So, I am not sure if JOSM maintainers would accept a break of this... hmm... consistency and add an exception for Germany, as it may open a precedent for adding more and more boundaries for different countries, making that file larger and larger in the process. But... you would need to ask them about that. After all, the file is not that large.
If they would be ok with adding this, then you'll need to provide the change to JOSM.
But, if this information is available, then enabling the smoking quest in certain regions of Germany would be possible.

**Comment by wetneb** [comment]
Ok! I thought StreetComplete used the boundaries file provided in the `data/` directory of this repository. If it is custom-generated then this issue belongs there instead, indeed!

**Comment by westnordost** [comment]
It does! But this IS the data from JOSM :-)
