### ISSUE TITLE
Java 8 / minSdkVersion 26 

### ISSUE THREAD

**Issue by simonpoole** [westnordost/countryboundaries#2]
As distributed this requires Java 8 and therefore at least SDK 26. Does the code actually have Java 8 dependencies? If not, could the requirement be removed?

**Comment by westnordost** [comment]
You are not using Android Studio? What then?

**Comment by simonpoole** [comment]
Will test without the compileSdkVersion change again, but the build tools were complaining bitterly originally. My dev environment is eclipse with buildship and a couple of gradle hacks to get the classpath right (which is becoming increasingly difficult as the goog really wants to twist everybody's arm to use AS). Works quite well and there is little that really doesn't work even with essentially no working android support in eclipse any more. 

Now eclipse is IMHO horrible on a number of counts, but in comparison to AS it is the pinnacle of UI design.

**Comment by simonpoole** [comment]
Yes, it does just require source/targetCompatibility setting, however that should be mentioned "somewhere".
