### ISSUE TITLE
Missing country for specific location (reproducible example with minimal dataset is provided)

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/countryboundaries#3]
Edit: skip to https://github.com/westnordost/countryboundaries/issues/3#issuecomment-471603570 to get to ready dataset + program reproducing this issue

----

With default data results are surprising given the project name - it return that location is within `EU` without returning country code.

I get output

```
[US-TX, US]
US
[US-NY, US]
US
[EU]
EU
```

for following code where I would expect `PL` for the last one.

```
import de.westnordost.countryboundaries.CountryBoundaries;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.List;

public class main {
    CountryBoundaries boundaries;
    public main() throws IOException {
        boundaries = CountryBoundaries.load(new FileInputStream("boundaries.ser"));
    }

    public static void main(String[] args) throws IOException {
        main test = new main();
        System.out.println(test.getCountryCode(-96.7954, 32.7816));
        System.out.println(test.getCountryCode(-77.6029387, 43.2077508));
        System.out.println(test.getCountryCode(20, 50));

}

    public String getCountryCode(double lon, double lat) {
        List<String> returned = boundaries.getIds(lon, lat);
        System.out.println(returned);
        return returned.get(returned.size() -1);
    }
}
```

**Comment by matkoniecz** [comment]
Also, it is surprising given `get country ids by position` comment in the Readme.

**Comment by matkoniecz** [comment]
Manually building from JOSM data using provided generator resulted in the same output.

**Comment by westnordost** [comment]
Wait, so the actual issue here is that countryboundaries returns `[EU]`, not `[PL, EU]` at lat=50, lon=20, right?

**Comment by westnordost** [comment]
In the example app, I cannot reproduce it, it is `PL,EU`. (Not exactly at 50,20, but when clicking around in the vicinity. Is it only reproducable at exactly 50,20, or what?
Which version of countryboundaries are you using?

**Comment by westnordost** [comment]
Oh, now I get it. The fault is at your own code. The result list is simply ordered by size of the area in which it is contained. If you want [EU](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#EU) out, you should either always filter it out of the result list before returning or use a different source data set. You can generate it rather easily, see `/generator/`.

**Comment by matkoniecz** [comment]
> Wait, so the actual issue here is that countryboundaries returns [EU], not [PL, EU] at lat=50, lon=20, right?

Yes.

> In the example app, I cannot reproduce it, it is PL,EU. (Not exactly at 50,20, but when clicking around in the vicinity.

I was not testing it with sample app, but with program posted above.

>  Which version of countryboundaries are you using?

1.4 as instruced in https://github.com/westnordost/countryboundaries#usage

**Comment by matkoniecz** [comment]
> If you want EU out, you should either always filter it out of the result list before returning or use a different source data set. You can generate it rather easily, see /generator/.

I just tried. Removing

```
  <relation id='-29642'>
    <member type='way' ref='-29584' role='outer' />
    <member type='way' ref='-29426' role='outer' />
    <member type='way' ref='-29026' role='outer' />
    <member type='way' ref='-29028' role='outer' />
    <member type='way' ref='-29030' role='outer' />
    <member type='way' ref='-29398' role='outer' />
    <member type='way' ref='-29386' role='outer' />
    <member type='way' ref='-29296' role='outer' />
    <member type='way' ref='-29430' role='outer' />
    <member type='way' ref='-28994' role='outer' />
    <member type='way' ref='-28992' role='outer' />
    <member type='way' ref='-28990' role='outer' />
    <member type='way' ref='-29412' role='outer' />
    <member type='way' ref='-29414' role='outer' />
    <member type='way' ref='-29200' role='inner' />
    <member type='way' ref='-29256' role='inner' />
    <member type='way' ref='-29428' role='inner' />
    <member type='way' ref='-28914' role='inner' />
    <member type='way' ref='-29180' role='inner' />
    <member type='way' ref='-29118' role='inner' />
    <member type='way' ref='-29106' role='inner' />
    <member type='way' ref='-29344' role='inner' />
    <tag k='ISO3166-1:alpha2' v='EU' />
    <tag k='name:en' v='European Union' />
    <tag k='type' v='multipolygon' />
  </relation>
```

resulted in my code crashing with

```
[US-TX, US]
US
[US-NY, US]
US
[]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at main.getCountryCode(main.java:24)
	at main.main(main.java:17)
```

**Comment by matkoniecz** [comment]
I run unit tests, all are passing so if it is some local malfunction then it is subtle enough to not get caught by tests. Currently my idea for the next step is to edit JOSM file again to remove everything except Poland and try again, if error persists then simplify Poland geometry to square and submit is in a PR as a failing unit test.

Or is it maybe obvious what is going wrong and I am not noticing it?

**Comment by westnordost** [comment]
I don't see anything obviously wrong

**Comment by westnordost** [comment]
I can also reproduce it

**Comment by westnordost** [comment]
Is it reproduceable with v1.2?

Thank you for drilling into the problem. Perhaps it is a problem with the point-in-polygon algorithm. To debug this (and finally write a test for it), it would be very useful to find a minimal example.

**Comment by matkoniecz** [comment]
> Is it reproduceable with v1.2?

I will start from a simple one and use `.ser` generate in .1.4 in client program using 1.2.

As expected it resulted no changes.

**Comment by matkoniecz** [comment]
I now tried to use .ser generate in `.1.2` in client program using `1.2`.

Resulted in the same output.

**Comment by matkoniecz** [comment]
I opened JOSM provided file in JOSM.

Its geometry looks OK, double clicking in Poland selects Poland area.

I also run a validator that reported no useful warnings.

So it looks like it is not a data issue.

**Comment by westnordost** [comment]
And if you move the point from 50,20 to sth slightly different, it will correctly return PL, right?

Could you try to find a minimal geometry with which 50,20 does not work but i.e. 50.00001,20.00001 does?

Am 11. März 2019 15:40:45 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>I opened JOSM provided file in JOSM.
>
>Its geometry looks OK, double clicking in Poland selects Poland area.
>
>I also run a validator that reported no useful warnings.
>
>So it looks like it is not a data issue.

**Comment by matkoniecz** [comment]
For now I reduced dataset to three triangles.

Now I will try to move point a bit and report results.

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' upload='never' generator='JOSM'>
 <node id='-1155835' lat='55.25302' lon='18.57853' />
 <node id='-1165353' lat='49.39557' lon='18.9742' />
 <node id='-1165423' lat='50.40481' lon='23.79445' />
 <node id='-1170403' lat='39.75306868232' lon='-72.86088898438' />
 <node id='-1170479' lat='42.00107' lon='-79.76349' />
 <node id='-1170503' lat='45.78087681' lon='-73.35025' />
 <node id='-1170837' lat='36.31731224423' lon='-94.86041885742' />
 <node id='-1171649' lat='26.55583574053' lon='-103.23051828125' />
 <node id='-1180635' lat='25.17512647438' lon='-91.69190551758' />
 <way id='-1180394' >
  <nd ref='-1155835' />
  <nd ref='-1165423' />
  <nd ref='-1165353' />
  <nd ref='-1155835' />
  <tag k='ISO3166-1:alpha2' v='PL' />
  <tag k='name:en' v='Poland' />
 </way>
 <way id='-1180395' >
  <nd ref='-1170479' />
  <nd ref='-1170403' />
  <nd ref='-1170503' />
  <nd ref='-1170479' />
  <tag k='ISO3166-2' v='US-NY' />
 </way>
 <way id='-1180396' >
  <nd ref='-1180635' />
  <nd ref='-1171649' />
  <nd ref='-1170837' />
  <nd ref='-1180635' />
  <tag k='ISO3166-2' v='US-TX' />
  <tag k='name:en' v='Texas' />
 </way>
</osm>
```

**Comment by matkoniecz** [comment]
Good news! Geometry above matches requirements of

> Could you try to find a minimal geometry with which 50,20 does not work but i.e. 50.00001,20.00001 does?

```
package de.westnordost.countryboundaries;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.GeometryCollection;

import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.StringReader;
import java.io.Writer;
import java.util.Arrays;
import java.util.Locale;
import java.util.Map;

public class Main
{
	public static void main(String[] args) throws Exception {

		if(args.length < 3) {
			System.err.println("Missing parameters. I.e. 'boundaries.osm 360 180' ");
			return;
		}

		String filename = args[0];
		int width = Integer.parseInt(args[1]);
		int height = Integer.parseInt(args[2]);

		FileInputStream is = new FileInputStream(filename);

		GeometryCollection geometries;
		if(filename.endsWith(".json") || filename.endsWith(".geojson"))
		{
			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			byte[] buffer = new byte[1024];
			int length;
			while ((length = is.read(buffer)) != -1)
			{
				baos.write(buffer, 0, length);
			}
			geometries = (GeometryCollection) new GeoJsonReader().read(baos.toString("UTF-8"));
		}
		else if(filename.endsWith(".osm"))
		{
			geometries = new JosmCountryBoundariesReader().read(new InputStreamReader(is, "UTF-8"));
		}
		else
		{
			System.err.println("Input file must be a OSM XML (.osm) or a GeoJSON (.json/.geojson)");
			return;
		}

		//String geojson = new GeoJsonWriter().write(geometries);
		//try(Writer writer = new OutputStreamWriter(new FileOutputStream("boundaries.json"), "UTF-8"))
		//{
		//	writer.write(geojson);
		//}

		for (int i = 0; i < geometries.getNumGeometries(); i++)
		{
			Geometry g = geometries.getGeometryN(i);
			g.setUserData(((Map)g.getUserData()).get("id"));
		}

		System.out.print("Generating index...");

		CountryBoundariesGenerator generator = new CountryBoundariesGenerator();
		generator.setProgressListener(new CountryBoundariesGenerator.ProgressListener()
		{
			String percentDone = "";

			@Override public void onProgress(float progress)
			{
				char[] chars = new char[percentDone.length()];
				Arrays.fill(chars, '\b');
				System.out.print(chars);
				percentDone = "" + String.format(Locale.US, "%.1f", 100*progress) + "%";
				System.out.print(percentDone);
			}
		});

		CountryBoundaries boundaries = generator.generate(width, height, geometries);
		try(FileOutputStream fos = new FileOutputStream("boundaries.ser"))
		{
			try(ObjectOutputStream oos = new ObjectOutputStream(fos))
			{
				boundaries.write(oos);
			}
		}
	}
}
```

goes down with

```
[US-TX]
US-TX
[US-NY]
US-NY
[PL]
PL
[]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at main.getCountryCode(main.java:25)
	at main.main(main.java:18)
```

**Comment by westnordost** [comment]
Will look at it now / this weekend

**Comment by westnordost** [comment]
So, the problem was this:
- The point in polygon algorithm that I use considers points on the **lower** and right edge not part of the polygon. (This is deliberate.)
- The raster that decides in which cell a lat-lon coordinate is (and thus to search for polygons that might contain the coordinate), considered points on the **upper** and right edge not part of the cell

So, when users queried points that were vertically exactly on a raster cell edge, the point was seemingly not in that polygon.

**Comment by westnordost** [comment]
Will release a new version today

**Comment by matkoniecz** [comment]
Thanks!
