### ISSUE TITLE
Is dummy ossrhUsername desirable?

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/countryboundaries#4]
With no changes to code attempt to build this on Intellij idea failed with

> Could not get unknown property 'ossrhUsername' for object of type
org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

Problem went away after I added to `gradle.properties`

```
group = dummy

ossrhUsername = user
ossrhPassword = pass
```

It does not look like a correct solution, so I am unsure whatever adding this would be desirable. If it would be a good idea let me know and I will open a pull request.

From https://docs.gradle.org/current/userguide/build_environment.html it seems that dummy variables would be overridden if user specifies them as System properties, but not if specified as Environment variables 

`ossrhUsername site:docs.gradle.org` querries failed to find this property and I am not sure why IntellijIdea (or gradle) is happy with dummy one but refuses to work if none is specified.

**Comment by westnordost** [comment]
done
